import CustomLink from "@/components/CustomLink";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <>
          <nav>
            <ul className="flex justify-center items-center gap-5 py-5">
              <li>
                <CustomLink path={"/dashboard/home"}>Home</CustomLink>
              </li>
              <li>
                <CustomLink path={"/dashboard/contact"}>Contact</CustomLink>
              </li>
              <li>
                <CustomLink path={"/dashboard/setting"}>Setting</CustomLink>
              </li>
              <li>
                <CustomLink path={"/dashboard/havy"}>Havy</CustomLink>
              </li>
              <li>
                <CustomLink path={"/blogs"}>Blog</CustomLink>
              </li>
            </ul>
          </nav>

          {children}
        </>
      </body>
    </html>
  );
}
